### ISSUE TITLE
(Windows) Client hangs on white screen on launch

### ISSUE THREAD

**Issue by pjburnhill** [vcmi/vcmi#1058]
On Windows, using display other than DISPLAY1 hangs on white screen on client launch. Fixed by changing default video driver in settings.json (mine worked using `direct3d11`).

- Using [VCMI-1.0.0-cedc9a9-Windows.exe](https://github.com/vcmi/vcmi/releases/download/1.0.0/VCMI-1.0.0-cedc9a9-Windows.exe)
- Only VCMI Essential files were installed
- Windows 10 19043.2006 Build
- Nvidia RTX 3090, latest drivers (517.40)
- Three displays attached, same issue on both DISPLAY2 and DISPLAY3

Log files don't show any issues:
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/9732550/VCMI_Launcher_log.txt)
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/9732551/VCMI_Client_log.txt)

Also, Windows paths to logs and settings.json were incorrect at https://wiki.vcmi.eu/Bug_reporting_guidelines. I've edited to point to correct locations.

Suggestion: Add option to switch default video driver in launcher

![2022-10-07 09_41_07-](https://user-images.githubusercontent.com/2419138/194523481-95da3e49-a319-4b5a-9609-ac58785acb71.png)

**Comment by Kyliathy** [comment]
I'm affected by the same issue. I also installed VCMI extensions. The application starts, but hangs. It only produces about 388 KB of log, before dying, always at the same line of the log. Something seems to be up with mr Roland.

@pjburnhill I'm willing to bet that if you end task you will see the same log I see below. Because my log is also just 14 KB to begin with, but if I kill the process, the log actually increases to 388 KB. Same behavior every time.

DEBUG mod [7d70] - Converting specialty format for hero roland(castle)
TRACE mod [7d70] - "specialty" : {
	"base" : {
		"duration" : [ "PERMANENT" ],
		"limiters" : { "type" : "CREATURE_TYPE_LIMITER" },
		"source" : "HERO_SPECIAL",
		"sourceID" : 152
	},
	"bonuses" : {
		"attack" : {
			"limiters" : { "parameters" : [ "griffin", false ] },
			"subtype" : "primSkill.attack",
			"type" : "PRIMARY_SKILL",
			"updater" : {
				"parameters" : [ 8, 3 ],
				"type" : "GROWS_WITH_LEVEL"
			}
		},
		"attack2" : {
			"limiters" : { "parameters" : [ "royalGriffin", fal

**Comment by Kyliathy** [comment]
Oh, and I tried changing the video driver, it didn't work.

**Comment by Povelitelh3** [comment]
@Kyliathy what about now? still reproducibility?

**Comment by Kyliathy** [comment]
Actually, it works with the lastest version! Good job! :)
