### ISSUE TITLE
Battle console activated when pressed outside it

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1249]
1. Start any battle
2. Press anywhere in area selected in red (see screenshot)
3. Press enter (or exit from pop-up menu and then press enter)

Expected result: console is activated only when pressed in its area
Actual result: console activated outside its area

Reproduced on 1.2, not reproduced on 1.1, assuming regressions after https://github.com/vcmi/vcmi/pull/1172 but cannot confirm

<img width="804" alt="Снимок экрана 2022-12-19 в 22 00 47" src="https://user-images.githubusercontent.com/9308612/208490813-47b17c0d-dcb5-4e5d-b17f-79f62d6f333e.png">

**Comment by IvanSavenko** [comment]
@Nordsoft91 
Caused by #1186 since that fix was pushed to beta and not yet in develop.

However irregardless of that fix in-game console has some bugs.
Since this mostly affects mobile platforms, how should clicking on status bar work?
Currently, only adventure map allows console activation via click. Should we apply same logic to all other status bars?

**Comment by IvanSavenko** [comment]
Ah, I think I figured it out:
- Status bar on adventure map interface should allow text input (via click or "Tab" key)
- Status bar in battle should also allow text input with same rules
- All other status bar's should not have text input

This is due CIngameConsole class - this is class responsible for rendering incoming text messages and it only present on adventure map and in battle. Mirroring status bar settings makes sense.
