### ISSUE TITLE
Consider setting Nullkiller AI as default one for adventure map in launcher

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#1288]
As in title - average player doesn't know this kind of stuff and may be disappointed by AI performance that he will see by default.
If nullkiller AI is considered more stable than VCAI then it is another reason to make it default, rather than defaulting to AI with higher chance of being stuck for infinite amount of time when it's performing its turn.

**Comment by Povelitelh3** [comment]
I completely agree. If a player does not like the problem due to the fact that he takes a long time to make his move, you can advise him to switch to VCAI.
And yet, in addition to all this, I would make battleAI by default, since it is a little better than stupid.
(stupid can't do a lot of things that the original can do: shoot backflows, burn with dragons, don't fall into the zone of impact of creatures, and go at once for the whole turn with creatures, as far as I remember)

**Comment by nullkiller** [comment]
I am not sure which AI is more stable. NKAI have changes time to time and thus new bugs) Also it might be slow for XL maps. Also because of bugs.

**Comment by dydzio0614** [comment]
And VCAI has no chances and people get stuck at same AI infinite loops

**Comment by kambala-decapitator** [comment]
> Also it might be slow for XL maps

currently playing on XL RMG map with 3 NKAI enemies, all good

**Comment by dydzio0614** [comment]
@nullkiller while VCAI is "stable", it is fairly buggy and many players consider its strength "unacceptable"
