### ISSUE TITLE
[Android] Right Click

### ISSUE THREAD

**Issue by JakubOwadowski** [vcmi/vcmi#1358]
**Describe your proposal**
Due to how the Android port works, the functions of the right click on desktop can't be accessed. A logical fix for that would be to tie it with touch-and-hold on mobile, letting you see the artifact descriptions and such this way.

**Comment by Laserlicht** [comment]
Which functions are meant exactly?

So at least the infobox works for me. With two fingers. First one finger on the "target", then a second finger somewhere.

**Comment by JakubOwadowski** [comment]
Oh, I guess. It's not very intuitive though, this would make it much more in line with how one expects games to work on mobile.

**Comment by Mr-Bajs** [comment]
As of now you have to a two finger click with at the same time to do a right click press. It doesn't work very well. The fheroes2 procjet for homm2 on android, did the right click so that you first press one finger on the thing that you want to right click and THEN with you second finger presses somewhere on the screen. 
It works better than being to press with two fingers att the exact same time. I would suggest that VCMI takes the same approach as fheroes2, because it works pretty well.

**Comment by ttyborg** [comment]
Touch-and-hold as an option would also make playing with a stylus better.

**Comment by Laserlicht** [comment]
Yes, press and hold would be good. Maybe we could port the behavior from iOS. I personally find that pleasant and intuitive.
