### ISSUE TITLE
Outdated daily build for android

### ISSUE THREAD

**Issue by jcgamp** [vcmi/vcmi#1495]
Daily builds for android (https://builds.vcmi.download/branch/develop/Android/) seem quite outdated with the latest one from november. iOS, Windows & macOS builds are being built every night

**Comment by kambala-decapitator** [comment]
yes, we're aware of that.

as a workaround, you can download builds from https://github.com/vcmi/vcmi-android/actions. Currently the latest is https://github.com/vcmi/vcmi-android/actions/runs/4002483138

**Comment by jcgamp** [comment]
so as I see it, as of now there is no way to test the newest features (develop branch) on an android device?

**Comment by kambala-decapitator** [comment]
not really unless you build from source on your own

**Comment by jcgamp** [comment]
I was looking the wiki site for instructions how to build it from source (iOS, macOS, Windows & Linux have them) but with no avail, do you have a tutorial how to do that?

am I wrong or android is a bit neglected overall? :)

**Comment by kambala-decapitator** [comment]
unfortunately, no tutorial afaik, but you can check CI steps to figure out what you need to do: https://github.com/vcmi/vcmi-android/blob/master/.github/workflows/github.yml

we don't have a more or less professional android dev to implement native platform features, if that's what you mean. Currently one of our core devs is working on android part to release update on the Play Store and that uses `beta` repo branch instead of `develop`. Once that is done, daily builds from `develop` will appear again.

**Comment by kambala-decapitator** [comment]
oh, seems there's actually something like build instructions: https://github.com/vcmi/vcmi-android/blob/master/building.txt

**Comment by jcgamp** [comment]
great! thanks you! will try to build and try it a bit :) 

regarding android features, I've noticed that iOS has a bit more QoL features implemented (or on PRs) so I assumed that android is a little behind with the features. But it's quite understandable considering your lack of android developers
