### ISSUE TITLE
ALT shortcut for showing Movement cost does not start to work unless you move the mouse

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#1632]
**Describe the bug**
Pressing ALT does not start showing in status window the movement cost and remaining movement points unless mouse is also moved.

**Expected behavior**
Instantly when I press ALT I get the movement info shown in status bar. (like in HotA)

**Version**
 - OS: Windows
 - Version: develop

**Comment by dydzio0614** [comment]
Not exactly bug IMO since it's extra feature and not obliged to work exactly same as in hota (general functionality is maintained anyway). Maybe could be interested "bug in extra feature" since lack of instant reaction is not very intuitive.

But your suggested behavior is small improvement anyway, so if can be fixed with small effort then why not.
