### ISSUE TITLE
add what advmap objects do to their RMB description 

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#1668]
Not all objects show their bonuses in description, example:
![Screen Shot 2023-03-10 at 20 19 58](https://user-images.githubusercontent.com/1557784/224411977-8a0a9612-432d-410a-aa4e-ac973e929d7d.png)

I suggest to add bonuses to this info as a useful deviation from oh3. For example I tend to forget which objects give morale and which give luck.

**Comment by IvanSavenko** [comment]
FYI:
1) some objects give different reward based on current day (e.g. Idol of Fortune can give luck, or morale or both luck & morale, depending on day)
2) some objects give randomly selected reward - Fountain of Fortune gives random amount of luck & resets its random value each week.

Not against such option, but we should think how to handle such cases. Maybe manually written description string would be better. Especially since we have translations now.

**Comment by DjWarmonger** [comment]
We added these descriptions to object names in some upcoming mods (HoTA, WoG 1.2 + my own inventions) so players who see the object for a first time can have a clue what it does.

**Comment by IvanSavenko** [comment]
Implemented in 1.4
