### ISSUE TITLE
VCMI launcher freeze 

### ISSUE THREAD

**Issue by psyhlo** [vcmi/vcmi#1787]
EDIT: Windows version, dont know it is the same for other platform 
**Describe the bug**
VCMI launcher freeze when installing/updating mod. I think it freeze when downloaded archive is extracting.

**To Reproduce**
1. Open VCMI Launcher
2. Mark mod
3. Install/Update it
4. It freeze for a while

**Expected behavior**
Not to freeze, may be show some notification that it is working on something

**Comment by psyhlo** [comment]
I tested in linux, it was the same behaver

**Comment by Nordsoft91** [comment]
To fix that, we actually need to specify size per each mod, as it doesn't come from GitHub

**Comment by rilian-la-te** [comment]
@Nordsoft91 no, I do not think so, we need only download in another thread and use QProgressBar with both minimum and maximum as 0 (then it will be just a busy indicator).

**Comment by IvanSavenko** [comment]
1) This is not what this issue is about. Issue is about freeze that occurs *after* download is complete, I think Launcher unpacks/copies downloaded zip archive in event thread. leading to a freeze

2) Broken download progress is a separate issue. Github does not provides this info - try downloading any mod manually, via browser, e.g. hota:
https://github.com/vcmi-mods/horn-of-the-abyss/archive/refs/heads/vcmi-1.2.zip
Browser also fails to estimate download size & only displays elapsed time & download size. I guess we could do the same - can't exactly rely on modders to always provide correct download size in mod.json

**Comment by psyhlo** [comment]
> 2. Broken download progress is a separate issue. Github does not provides this info - try downloading any mod manually, via browser, e.g. hota:
>    https://github.com/vcmi-mods/horn-of-the-abyss/archive/refs/heads/vcmi-1.2.zip
>    Browser also fails to estimate download size & only displays elapsed time & download size. I guess we could do the same - can't exactly rely on modders to always provide correct download size in mod.json

i think i catch this issue too. If you have more then 1 repo. Launcher shows you correctly that mod has new version but downloads the mod from the first repo.
![image](https://user-images.githubusercontent.com/1803170/229371714-87c24a74-6567-4c90-a4cc-b0717fcaa486.png)

mod has new version in beta.json, but launcher download it from github.json
