### ISSUE TITLE
[Android] Game window shrinks when switching apps

### ISSUE THREAD

**Issue by lje** [vcmi/vcmi#1794]
**Describe the bug**
When I start a new game, pay it and then switch to another app (putting VCMI to background) and then switch back to VCMI, trhe game window shrinks and large black borders are addes (see screen shot).

**To Reproduce**
1. start VCMI
2. start a new game
3. switch to another app
4. switch back to VCMI

**Expected behavior**
Game shoud be full-screen after switching back

**Actual behavior**
Game window shrinks, black borders added

Workaround currently is to end/force close VCMI, start new, load game.

**Did it work earlier?**
Yes. This seems to be a regression in 1.1 (or 1.0, which I didn't use due to other bugs in the Android version). It did work fine in 0.9x

**Screenshots**
Launcher / Selected resolution
![Screenshot_20230328_213125_VCMI](https://user-images.githubusercontent.com/357743/228443382-2f388921-a5ff-4bf9-a498-f5feaaa4adfc.jpg)

Starting to play
![Screenshot_20230328_213151_VCMI](https://user-images.githubusercontent.com/357743/228443456-9c27f183-ecfd-478b-a794-ce634b143028.jpg)

After switching to another app and back to VCMI
![Screenshot_20230328_213203_VCMI](https://user-images.githubusercontent.com/357743/228443529-9964b41d-be1c-4365-bbba-3221f8a70fe6.jpg)

**Version**
 - OS: Android 13
 - Version: 1.1.0

**Additional context**
Device is a Galaxy Tab S8+, native resolution 2800 x 1752, so VCMI needs to scale the selected 1366 x 768 to that resolution. Maybe the scaling is messed up when switching?

**Comment by kambala-decapitator** [comment]
could you test if the same happens in the latest daily build? https://download.vcmi.eu/branch/beta/Android/aarch64-v8a/

**Comment by lje** [comment]
I did, the issue is present in [VCMI-branch-beta-3e1506d.apk](https://download.vcmi.eu/branch/beta/Android/aarch64-v8a/VCMI-branch-beta-3e1506d.apk) as well.

**Comment by IvanSavenko** [comment]
Might be fixed in my PR.
Fix should be available in next daily bulid (May, 12) from here tomorrow:
https://download.vcmi.eu/branch/develop/Android/arm64-v8a/

**Comment by ViaFerrata** [comment]
Tried out today's daily build and seems to be fixed.

Off topic:

However, some other commits seem to have modified the resolution / UI.
Now at 800x600 the main menu is very small (like if you would set very high resolution).
Using 300% resolution scaling kind of reverts it back to roughly 800x600, but UI is still significantly different since 800*600 UI is different than an upscaled high resolution.
For example, the town view is not fullscreen anymore due to filling the whole widescreen instead of black bars.

800x600, today's build, with 100% resolution scale:
![Screenshot_20230609_202721](https://github.com/vcmi/vcmi/assets/19201882/683a612c-b595-44af-9e6a-62d3ff85cb6b)

800x600, today's build, with 300% resolution scale:
![Screenshot_20230609_202651](https://github.com/vcmi/vcmi/assets/19201882/64587cc7-9073-4a2f-a948-b7720b56f762)
![Screenshot_20230609_202536](https://github.com/vcmi/vcmi/assets/19201882/c3839085-4f1b-443c-a85f-7099e0585fc8)

**Comment by IvanSavenko** [comment]
> Now at 800x600 the main menu is very small (like if you would set very high resolution).

> This is on a Tab S8+ with 1752x2800 display.

Yeah, kind of expected... We should probably have interface scaling of at least 200% as default for mobile platforms.
Noted.

> For example, the town view is not fullscreen anymore due to filling the whole widescreen instead of black bars.

Intended I guess? This is how VCMI handles resolutions with aspect ratios different from H3 default (3x4)

**Comment by ViaFerrata** [comment]
> Intended I guess? This is how VCMI handles resolutions with aspect ratios different from H3 default (3x4)

I think so, just wanted to mention that this behaviour has changed.
Or is it still possible to get a non-stretched game screen (i.e. black bars at the border), like with setting 800x600 using v1.2.1?

I was also not sure if this has an effect on the "crispness" of the game. 
Though setting 800x600 with v1.2.1 was not really 800x600 as well (it filled whole vertical space of my 1752 pixel screen), I guess there has always been additional, automatic scaling?

Based on ScummVM and JA2 Stracciatella on Android I know that resolution and scaling is quite an exhaustive topic.
In JA2 Stracciatella for example it's best to use a resolution fitting the screen 1:1, otherwise the interpolation/scaling makes the game quite blurry. Same for ScummVM, though there are some good filters applied after scaling.

**Comment by IvanSavenko** [comment]
> Or is it still possible to get a non-stretched game screen (i.e. black bars at the border), like with setting 800x600 using v1.2.1?
Probably not. Only if you have 3x4 screen.
Screen handling in 1.2.1 was rather poorly done, leading to multiple bugs, like the one reported here. So in daily builds / in 1.3 VCMI will always cover entire screen on Android.

We might add optional black borders to screen to handle reserved areas on iOS (and possibly Android) - e.g. camera cutout, so if you really want you might be able to restore 1.2.1 behavior

> I was also not sure if this has an effect on the "crispness" of the game.

For maximum "crispness" you might want to select integral interface scaling - 100%, 200%, 300%*. Aspect ratio is not important - vcmi adapts to display aspect ratio without any scaling.
* note that in your case 300% is not actually 300%, but actually ~292% - maximum for your screen, will think about making it more clear in UI.

That being said, I personally haven't noticed any bad scaling effects even at non-integral scaling ratios - H3 graphics are mostly pre-rendered 3d models and not pixel-art, so it scales reasonably well.

**Comment by ViaFerrata** [comment]
Thanks a lot for the detailed explanation!
