### ISSUE TITLE
Game crash if music files are missing

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#1836]
**To Reproduce**
1. Remove mp3 folder from data folder
2. Install and enable Forge mod
3. Start random map with forge town (must be on asphalt terrain)
4. Enter and leave you castle
5. Move hero at asphalt tile

**Expected behavior**
everything goes well

**Actual behavior**
client crash

**Version**
VCMI 1.1.0, 1.1.1

The root cause is "grass.mp3" soundtrack specified in
/forge/Mods/asphalt-terrain-mod/Content/config/terrains.json

Not reproduced in vanilla game

**Comment by rilian-la-te** [comment]
Maybe this is a forge mod bug, not VCMI one?

**Comment by misiokles** [comment]
offtop: with vcmi-1.2 release, asphalt mod will be extracted from Forge and become independed terrain mod. Then all techno-towns will use it as base terrain. And asphalt mod will contain its own music theme (from Antagarich burning).

**Comment by Nordsoft91** [comment]
@rilian-la-te , it's VCMI one, because if music is absent, no crash is expected

**Comment by Nordsoft91** [comment]
@misiokles , don't like this approach. Following this logic, we should extract all new terrains into separate mods (from hota for example).
Instead I suggest:
- main forge mod
--- forge1 town submod
--- asphalt terrain submod
- forge2 town mod

**Comment by misiokles** [comment]
Every solutions has their own pros and cons.
The biggest con is fact that MDT Team never made asphalt terrain. This submod was made not so long with various assets from the net (mostly Fred79 objects). So extracting it from mdt forge will avoid possible misunderstandings. It's better shift it to Andruid's Forge2k mod because if Forge is combined in similar way. HotA terrains have hota authors, so their native habitat is within hota submods :)
