### ISSUE TITLE
Ivor learned Necromancy from Scholar

### ISSUE THREAD

**Issue by krs0** [vcmi/vcmi#2139]
**Describe the bug**
Ivor learned Necromancy from Scholar

**To Reproduce**
1. On map all for one, random scholar gave Ivor Basic Necromancy

**Expected behavior**
No necro for non necropolis heroes 

**Screenshots**
![image](https://user-images.githubusercontent.com/15194321/236671836-bb5def63-8584-405c-b509-00a612c6f3a1.png)

**Version**
 - OS: [e.g. Windows, 
 - Version: debug

**Comment by IvanSavenko** [comment]
https://heroes.thelazy.net/index.php/Scholar_(Adventure_Map)
A Scholar can also teach a secondary skill that a hero cannot learn due to his [class](https://heroes.thelazy.net/index.php/Hero_class). For example, a Scholar can teach [Water Magic](https://heroes.thelazy.net/index.php/Water_Magic) to [Barbarians](https://heroes.thelazy.net/index.php/Barbarian).

So works as designed I guess?

**Comment by krs0** [comment]
Ok. Closed then.
