### ISSUE TITLE
Impossible to change resolution on iOS

### ISSUE THREAD

**Issue by Nordsoft91** [vcmi/vcmi#2178]
Impossible to changes screen resolution on iOS in both launcher and in-game menu.
It leads to some undesired effects, like main menu doesn't fit screen

**Did it work earlier?**
yes

**Version**
 - OS: iOS
 - Version: vcmi-1.3.0.10fc6cecef...

**Comment by IvanSavenko** [comment]
This part (non-selectable resolution) works as designed - on mobile systems (or with borderless window fullscreen on desktop) vcmi will always use screen resolution, in order to avoid bugs caused by different aspect ratio of game and screen.

Main menu doesn't fits the screen - should have been automatically adjusted via interface scaling. Not 100% sure what went wrong here...

**Comment by Nordsoft91** [comment]
another problem: as screen is not rectangular, some pieces are completely invisible - like day number (or even worse - whole list of towns if screen is rotated).
Before it was solved by having black strips in iPhone-specific resolution.
![Фото 21 05 2023, 22 47](https://github.com/vcmi/vcmi/assets/9308612/fdccc10b-f3d5-48fd-a31c-fdc236a27d00)

**Comment by Nordsoft91** [comment]
FYI https://github.com/vcmi-mods/vcmi-extras/commit/0a9567cf326a0b10998c58d64bffcaa0182615f7
