### ISSUE TITLE
Valley of Death Heroes raise skeletons rather than skeleton dogs

### ISSUE THREAD

**Issue by cinnamon189** [vcmi/vcmi#2274]
After a victorious battle, Valley of Death Heroes always raise enemies as skeletons rather than skeleton dogs. Indeed, that's even what the description of their Necromancy ability says, but I'm sure I once saw a video where they were supposed to raise skeleton dogs. If this has been changed at some point, please make it more explicit in the change log of the mod.

VCMI 1.2.x is the first branch I'm playing.

I'm on Windows 10 and used the English "Purple Hill" edition to get VCMI running. I was using the standard mods, WoG, German Translation, High-res Menu, Resourceful AI and most of the "Town" mods.

**Comment by misiokles** [comment]
Known bug in 1.2.x. Not fixed yet.

**Comment by cinnamon189** [comment]
Oh. Sorry, I searched the bug database but seem to have overlooked it...

**Comment by misiokles** [comment]
Fixed in Death Valley v1.30. Please, update mod by launcher (but saves will become broken).

**Comment by cinnamon189** [comment]
Wow, thank you for the super quick reaction :D Not sure whether this is the right place for this, but the ability is erroneously called "Martial Arts" and can raise a skeleton dog even if the enemy had zero losses. Also, Death Valley Heroes can still learn standard Necromancy - I guess this is unintentional. Finally, do artefacts that boost standard Necromancy also affect the new Necromancy?

**Comment by misiokles** [comment]
Hm... Version 1.2.0 brought big changes in bonus system, so nobody tested all modding possibilities and...potential bugs :)
It was my **quick** impression how to fix issues with death valley heroes. Now it's time to gather all new issues what can be improved/alterred/changed. That's why I don't know how necromancy artifacts affect such quickly made new skill :) And how system behave if hero knows Necromancy and Martia Art in the same time...!
