### ISSUE TITLE
UI is not locked while random map is being generated

### ISSUE THREAD

**Issue by IvanSavenko** [vcmi/vcmi#2286]
**Describe the bug**
While game generates random maps UI remains active and there is no indication that random map is being generated. This is especially noticeable for large maps on weaker systems (e.g. Android).

**To Reproduce**
1. Start a game
2. Attempt to generate random map (especially large ones)
3. Try to use UI while map is generated

**Expected behavior**
Possible alternatives:
a) Game displays map generation progress in a small window (H3 way)
b) Game switches to loading screen immediately once map generation starts

**Actual behavior**
There is no indication that map is being generated, UI is not locked and can be interacted with

**Did it work earlier?**
Unknown, probably not

**Version**
 - VCMI 1.2

**Comment by DjWarmonger** [comment]
Well, we don't have loading progress bar in first place.
Even though RMG offers API for that, whcih already works in the editor.

**Comment by dydzio0614** [comment]
IMO 1st alternative should be used to allow generation cancelling when we get more template features and map does not meet some validation - it is way easier to react to wrong generation furing actual generation (for example because mandatory zone object did not fit) than creating overcomplicated math algorithms to detect potential template flaws in theoretical corner cases of zone placement etc.

**Comment by DjWarmonger** [comment]
Wat? :v

- Maps should be generated in seconds, no reason to interrupt anything
- If generator fails to place some object (or road), it will report the issue in console

**Comment by dydzio0614** [comment]
for competitive reasons it should allow players to abort playing map that didn't generate all necessary objects etc. before they find that out ingame
