### ISSUE TITLE
Creature window shows bonuses from heroes skills.

### ISSUE THREAD

**Issue by misiokles** [vcmi/vcmi#2417]
**Describe the bug**
I'm not sure if it's bug itsefl, can be treated as cool idea, but needs polishing (icon display).
When hero knows armorer skills, Reduce Damage ability is showed also as creature ability. 

**Game logs**
![image](https://github.com/vcmi/vcmi/assets/29593042/c1993e87-c4c5-4964-84f9-d809cc307b73)

**To Reproduce**
1. Start any game
2. Choose Marius (Inferno hero) as starting hero.
3. After game launch click at creature info in her army.
4. See issue.

**Version**
 - OS: Windows
 - Version: beta-5f1af86

**Comment by DjWarmonger** [comment]
By design I guess? Creature window shows all creature bonuses from all sources, including artifacts and spells.

Now that we have unified secondary skills with bonus system, it's only more consistent.

**Comment by rilian-la-te** [comment]
@DjWarmonger I agree. In heroes V, creature window also shows this information.

**Comment by rilian-la-te** [comment]
I think it is a feature, not a bug.

**Comment by dydzio0614** [comment]
for me it's a bug xD

**Comment by rilian-la-te** [comment]
@dydzio0614 why it is a bug? I think, it is good than we can see bonuses on creatures? Or you want pure H3 and remembering all skills?

**Comment by dydzio0614** [comment]
you cannot distinguish creature abilities from the rest

**Comment by rilian-la-te** [comment]
@dydzio0614 so, maybe we need to show a bonuses with SECONDARY_SKILL source with secondary skill image and title? And not hide it altogether?

**Comment by IvanSavenko** [comment]
Got identical issue with bonus from artifact today. Have to admit that this somewhat confusing, but useful if you're aware of this.

Would be nice to have clear indication of bonus source.

For example, show only bonus name (e.g. "Reduce damage 10%") and bonus source - ability, hero skill, artifact, etc. Either just source type ("Artifact", "Secondary Skill") or concrete name of bonus source, ("Offence", "Pendant of Free Will")
Description can go to popup menu and can be made way longer instead of short one that we try (often unsuccessfully) to fit into tiny space here.

**Comment by DjWarmonger** [comment]
Yes, it would be a desired solution to list all the individual bonuses in a popup.

But the whole idea is that bonuses from various sources stack.

**Comment by luk3ZPL** [comment]
Maybe just different font color for bonuses added from skills and Viola ?

**Comment by krs0** [comment]
Fix by #4864
