### ISSUE TITLE
Crash on loading a save with missing mods on Android

### ISSUE THREAD

**Issue by jcialkowski** [vcmi/vcmi#2516]
**Describe the bug**
Loading saved games that were saved with missing mods can cause crashes on Android. While this issue may also occur on PC, the result is a crash on mobile, whereas on PC, only the load game window closes. It may require 2-3 attempts to reproduce the bug

**To Reproduce**
1. Save several games with certain mods loaded.
2. Uninstall the mods.
3. Attempt to load the saved games multiple times.

**Did it work earlier?**
no idea

**Screenshots**

https://github.com/vcmi/vcmi/assets/33762148/d8558a6d-8efd-42f2-8793-c100080eb6ef

**Version**
 - OS: android/linux
 - Version: 1.3

**Comment by IvanSavenko** [comment]
Moving to 1.4
Unfortunately not fixable without breaking save compatibility with 1.3.0 saves.

We probably need to completely kill our unfinished, partially working, slow and buggy json serializer. Because I lost count of how many issues related to it I have fixed already and still keep finding more.

This time json serializer attempts to access & resolved game identifiers before actually loading those identifiers. Apparently our async identifiers resolved was too hard and its implementation was not using enough template magic like Json serializer does.
