### ISSUE TITLE
Graphical artifacts in intro video

### ISSUE THREAD

**Issue by Alexander-Wilms** [vcmi/vcmi#3025]
**Describe the bug**
The Catherine intro video shows graphical artifacts:

* dark pixels in places where there is motion
* differences in color
* lower resolution
* stretched video and thus a different aspect ratio

when compared to playing H3INTRO.SMK with VLC

**Game logs**
na

**To Reproduce**
1. Start VCMI
2. Observe intro video
3. Extract videos from VIDEO:VID: `wine mmarch.exe extract VIDEO.VID VIDEO_VID`
4. Play H3INTRO.SMK with VLC

**Expected behavior**
No artifacts when played with either VLC or VCMI

**Actual behavior**
Various artifacts when played with VCMI

**Did it work earlier?**
unknown

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/3226457/f733157d-86dd-448f-8949-e5e8af2151f0)

![image](https://github.com/vcmi/vcmi/assets/3226457/a8096262-ab36-4bb0-9209-09ba530d6760)

![image](https://github.com/vcmi/vcmi/assets/3226457/23648573-486a-47be-a312-ab1f7dcfbd60)

**Version**
 - OS: openSUSE Tumbleweed
 - Version: 1.3.2 and develop

**Additional context**
One of the frames above in VLC for reference:
![vlcsnap-2023-10-08-13h39m28s898](https://github.com/vcmi/vcmi/assets/3226457/1b5498eb-6fbc-464c-832a-8056b24d7d75)

**Comment by Laserlicht** [comment]
If someone want to look into this:
Maybe it's similar to sound crackling was present on current audio PR.

The problem there was that in this case using linesize wasn't a good idea because (in comments of linesize):
`The linesize may be larger than the size of usable data -- there may be extra padding present for performance reasons.`

**Comment by Alexander-Wilms** [comment]
Interestingly, OH3 Complete from GOG running with Wine shows the same pixelation, black pixels and color difference.

So this would be an enhancement.

**Comment by Alexander-Wilms** [comment]
I added the rim and fixed the aspect ratio.

In order to debug the artifacts, it might be helpful to export the data decoded by libav, similar to your export of the sound data with the crackle.

`AV_PIX_FMT_YUV420P` and `SDL_PIXELFORMAT_IYUV` match what VLC shows, but https://ffmpeg.org/doxygen/3.4/pixfmt_8h.html lists several different `AV_PIX_FMT_YUV420P` macros for different bit depths, like `AV_PIX_FMT_YUV420P9` or `AV_PIX_FMT_YUV420P10`

**Comment by Laserlicht** [comment]
Just as reference from discord, if someone want to work on this:
- BIK video have better quality and no artifacts
- VCMI currently prefers SMK (because it was first found in the resources) -> to avoid delete `{".SMK",   EResType::VIDEO}` from `ResourcePath.cpp`
- VCMI currently supports only audio extraction from SMK

Possible Solutions:
- Fix problem for SMK in upstream ffmpeg lib and push ffmpeg version
- Prefer BIK
  - Load audio from SMK and video from BIK (workaround)
  - Extend audio extraction -> Decode BIK [similar](https://github.com/vcmi/vcmi/blob/ab7caa07772b2cea9a0342442617c4b258935a88/client/CVideoHandler.cpp#L562C1-L562C29) than SMK or better: Use libav to extract and convert audio to wav (for feeding SDL_mixer), which should then support all formats

**Comment by IvanSavenko** [comment]
I think it is actually fixed by #3998 
Or at the very least, all points from this comment should be fixed:

> * BIK video have better quality and no artifacts
> 
> * VCMI currently prefers SMK (because it was first found in the resources) -> to avoid delete `{".SMK",   EResType::VIDEO}` from `ResourcePath.cpp`
> 
> * VCMI currently supports only audio extraction from SMK

- bik is now preferred (to be precise - smk is used only as last resort)
- audio extraction should work with any format supported by ffmpeg
