### ISSUE TITLE
Coronius specialty is broken

### ISSUE THREAD

**Issue by Povelitelh3** [vcmi/vcmi#3288]
Errors in console. Just press end turn.
No mods.

```
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 7
CSpell::getLevelInfo: invalid school level 6
CSpell::getLevelInfo: invalid school level 5
CSpell::getLevelInfo: invalid school level 6
```

**Version**
 - OS: [e.g. Windows10]
 - Version: [VCMI version 1.4]

[1.zip](https://github.com/vcmi/vcmi/files/13627250/1.zip)

**Comment by IvanSavenko** [comment]
1) Slayer spell actually affects even creatures without(!) KING bonus. Trivial fix, will add to 1.4.1

2) Looks like Coronius specialty is broken:
- SLAYER bonus uses 'val' to determine countered KING tier
- SPECIAL_PECULIAR_ENCHANT modifies 'val' of bonus according to targeted creature tier
- Damage calculator accounts for SLAYER spell and adjust spell effect power accordingly

As result, if Coronius casts Slayer spell on tier-1 (e.g. Centaur), target receives SLAYER with val of (master + bonus = 0 + 4) even though code that checks for Slayer bonus expects 'val' to indicate KING level (instead of additional attack bonus)
