### ISSUE TITLE
Same date & time of all autosave games

### ISSUE THREAD

**Issue by tmysik** [vcmi/vcmi#3311]
**Describe the bug**
If you want to load an autosave game, all of them have the same date & time so it is not possible to find out which is the latest one.

**Game logs**
Sorry, no logs, I am on Android.

**To Reproduce**
1. Play game, several rounds
2. Try to load an autosave game
3. All of them have the same date & time

**Expected behavior**
At least time of the saved games should be different.

**Actual behavior**
All the saved games have the same time (and dates).

**Did it work earlier?**
Yes, it worked okay before 1.4 version.

**Screenshots**
No screenshot.

**Version**
 - OS: Android
 - Version: 1.4.0 & 1.4.1

**Additional context**
Nothing.

**Comment by Eivis24** [comment]
Been experiencing this bug since late September. I have 3 known builds ( VCMI-branch-develop-b89fa25.apk (bugless) ; VCMI-branch-develop-8c6381b.apk ; VCMI-branch-develop-47a17cc.apk ) of which at least one (if not all) doesn't have the mentioned bug.
Also the commit that started the bug may have been one of in the following list:
https://github.com/vcmi/vcmi/compare/724eb7902e2c36fab40ded7f60d105edab699fbd...4d43562bcafaf9848681f71996ac420f50b42a9e

Thought someone else will figure this out earlier.

**Comment by tmysik** [comment]
For me, it started in 1.4.0. If I am not wrong, I saw in its changelog something about date formatting on Android. That would be my guess (I cannot verify it on other platform ATM).

**Comment by Eivis24** [comment]
So i checked the build VCMI-branch-develop-47a17cc and it has the bug.

I'm very unlikely to fix the bug since i don't have enough (or any for that matter) experience in coding.

I'm writing this in hope that someone capable will be able to use my provided info.

**Comment by lje** [comment]
The problem seems to be that the function `getFormattedDateTime()` apparently is not intended to format arbitrary date/time - it does not have any parameter to pass da date/time. The function can only return the **current** date/time formatted - and that is exactly what happens: for all save games the current date/time is being displayed.

```
    public static String getFormattedDateTime()
    {
        String currentDate = new SimpleDateFormat((new SimpleDateFormat()).toLocalizedPattern(), Locale.getDefault()).format(new Date());
        return currentDate;
    }
```

This function is unsuitable to return the date/time of a save game.

**Comment by tmysik** [comment]
@lje Thanks for the investigation! Hopefully, it will be fixed soon.

**Comment by Laserlicht** [comment]
Will look for a solution

**Comment by tmysik** [comment]
Thanks a lot!

**Comment by tmysik** [comment]
I can confirm that the latest VCMI update fixed this issue. Thanks a lot!
