### ISSUE TITLE
Game stuck on 'Connecting' window

### ISSUE THREAD

**Issue by AndreySafronenko-VRP** [vcmi/vcmi#3557]
**Description**
Game stuck on 'Connecting' window. The issue is reproducible on any game type: campain, scenario, online game
<img width="317" alt="Screenshot 2024-01-24 at 13 16 11" src="https://github.com/vcmi/vcmi/assets/45426974/282f247b-ad0f-41b7-9e20-67ab4f562f90">

**Game logs**
[VCMI_Client_log.txt](https://github.com/vcmi/vcmi/files/14036778/VCMI_Client_log.txt)
[VCMI_Launcher_log.txt](https://github.com/vcmi/vcmi/files/14036780/VCMI_Launcher_log.txt)

**Version**
- OS: macOS Intel, macOs Ventura 13.6
- VCMI version: 1.4.4

**Comment by swats-the-floran** [comment]
i encountered such problem because the server was already launched or the port was wrong.
you can check port here
![image](https://github.com/vcmi/vcmi/assets/38055017/9d7f169e-2a14-4719-bcb7-fd4db1206756)
and try to manually stop vcmiserver task in macos task manager if it encountered some problem and not responding.

**Comment by AndreySafronenko-VRP** [comment]
@swats-the-floran thanks, that works. Just changed the port
