### ISSUE TITLE
Minor campaigns bugs

### ISSUE THREAD

**Issue by dydzio0614** [vcmi/vcmi#3601]
1. Map region should blink for short while on opening campaign scenario startup screen as in H3
2. If multiple scenarios are possible to be selected, VCMI doesn't pick first one - for example in Armageddon's Blade campaign Gelu mission gets picked by default

**Comment by Povelitelh3** [comment]
![001](https://github.com/vcmi/vcmi/assets/36762538/42a5cba0-5407-4bd6-82cc-5514730dfd6b)
![002](https://github.com/vcmi/vcmi/assets/36762538/488f1c03-2016-4fb6-b2c9-1bb63ea24569)
Good ticket. I will add. I didn’t want to create it separately because of this.

If you defeat this mission with a cheat code, the game crashes with the following error. But if you dismantle the alliance so that the game can take the sandals of the saints, then everything is fine.
(It's very easy to reproduce, win with vcmisilmaril)
