### ISSUE TITLE
Quick combat issue

### ISSUE THREAD

**Issue by by003** [vcmi/vcmi#3608]
Using a quick combat while defending the town, if lose in quick battle and reject the result, even win the battle by manual, the town will still become AI’s. 

In 1.50 development build. I think @Laserlicht need to know this because he made the quick combat function.

**Comment by Laserlicht** [comment]
Not tested this case. Do you have a save? Where ai attacks your castle, quick combat loses, but you're able to win.

**Comment by by003** [comment]
Try to use one arch devil versus 300 gnolls.

**Comment by Laserlicht** [comment]
Not sure if I can find the issue. The main work from quickbattle implementation itself are from are from @Nordsoft91 and @dydzio0614.

If someone want to find the issue: go for it. Otherwise I can try my best... In worst case we can still disable it for castle fightings.

**Comment by by003** [comment]
This issue was found in quick combat with other AI players and sometimes it will cause a crash while rejecting the result. If quick combat is not finished thoroughly, it can be blocked in next version.

**Comment by by003** [comment]
Still exists in latest build

**Comment by Laserlicht** [comment]
@IvanSavenko The issue here seems that the ai is continuing and not waiting for selection or restart battle (but it seems only when the ai attacks castles).

Do you have an idea? Queue code in combination with transfer over network and to ai code is really confusing to me. I can't get any further. Any easy ideas?

Reproduce:
1. Open save [test_bug.vsgm1.zip](https://github.com/vcmi/vcmi/files/14410832/test_bug.vsgm1.zip)
2. enable quick combat (maybe also unlimited replay for multiple tests)
3. end day
4. don't accept
5. kill devil

Also detected triggered assert: `assert(!playerID.isValidPlayer() || status.getBattle() == UPCOMING_BATTLE);` in `AIGateway::battleStart` when there are only units in town (no hero). But this should be easier

**Comment by IvanSavenko** [comment]
Simple solution: keep quickcombat only if battle was initiated by human. And always run AI-led battles in manual mode. Should work since from what I understand this only a problem for AI-initiated battles.

Better solution:

What's happening right now:
- server sends `BattleResult` pack
- client receives this pack and propagates it via `battleEnd` call to all players
- AI receives `battleEnd`, assumes that battle is over and resumes his actions

What can be done to fix it:
- add new call, for example, `battleEndConfirmed`
- call `battleEndConfirmed` when client receives pack `BattleResultAccepted` pack (already exists, but empty handling on client)
- make AI act only when it receives `battleEndConfirmed` call

Not 100% sure whether this will fix all of these issues, but should help I think.

**Comment by Laserlicht** [comment]
Update after debugging:
AI is waiting correct. This is not the issue.

Problem is this one:
https://github.com/vcmi/vcmi/blob/54fefd34c7cf07a33abbc764fde8e72be04e4fc8/server/queries/BattleQueries.cpp#L30

This line should be only executed when `answer == 0`. But I've no idea how to do... Not possible to simply move to `CBattleDialogQuery::onRemoval`.

**Comment by IvanSavenko** [comment]
Thanks for investigation.
So this is probably not AI-specific - if player attacks enemy town and replays battle he might end up with same situation.
By the way - how that thing works with other objects? Also broken?
Heroes, garrisons, dwellings likely also use that line. And mines - if owner leaves guards.

Sorry, not familiar enough with queries... The only thing that comes to mind is to move that line someplace else, for example to `BattleResultProcessor::battleAfterLevelUp`
