### ISSUE TITLE
Banks show exact number of guards

### ISSUE THREAD

**Issue by DjWarmonger** [vcmi/vcmi#3832]
**Describe the bug**
Bank info windows, on visit or r-click, show exact number of guards, which makes them perfectly predictable.

**To Reproduce**

1. Enter any creature bank
2. See the exact number of guards

**Expected behavior**
Banks should show ranges , ie. "Horde (50-99)"

**Actual behavior**
Banks reveal the exact number of guards always.

**Did it work earlier?**
Don't think so, it's a new feature.

**Screenshots**
![image](https://github.com/vcmi/vcmi/assets/2566990/c94216c4-3f52-45fb-9f1b-054103f952a7)

**Additional context**
Important for PvP experience.

**Comment by IvanSavenko** [comment]
Not h3 feature. This is HD Mod feature. H3 shows no previews for bank size at all.

Was implemented deliberately this way. Reasoning:
- Since this is HD Mod feature, this is not something that we need to implement identically
- In many cases, those ranges are easy to predict - usually there is two or even just one possible configuration for such range. Crypt is most extreme example, where every preview is unique, despite ranges.
- Displaying precise amounts was also easier to implement - at the moment we don't have ranges support in such dialogs.

If somebody wants to implement it - go ahead. But IMO this is very low priority or not an issue at all. We have quite a lot of other features and bugs that we need to take care of first.
