### ISSUE TITLE
v1.5.0 release tarball lacks innoextract

### ISSUE THREAD

**Issue by Gigas002** [vcmi/vcmi#3923]
[These files](https://github.com/vcmi/vcmi/tree/develop/launcher/lib) are lacking from 1.5.0 release tarball

**Comment by kambala-decapitator** [comment]
I believe it's a GitHub issue that it doesn't pack submodules

you can build with `-D ENABLE_INNOEXTRACT=OFF`

**Comment by IvanSavenko** [comment]
Unfortunately Github tarball don't contain submodules for some reason.
Same goes to our other submodules - fuzzylite & google test.

You can either:
- use ENABLE_INNOEXTRACT=OFF flag, as suggested by kambala
- get our innoextract sources from here: https://github.com/vcmi/innoextract (or I can create separate 'release' for innoextract that would match what was used for 1.5)
- use `git clone --recursive` instead of tarball. This would also grab submodules

**Comment by Gigas002** [comment]
I see, no problem, will disable innoextract for a time being! :+1:

**Comment by kambala-decapitator** [comment]
but you won't be able to build AIs because they depend on fuzzylite

better clone the repo and checkout tag, then you can populate submodules

**Comment by Gigas002** [comment]
Yeah, I've been using `-DFORCE_BUNDLED_FL=OFF` to not trigger problems with fuzzylite, I've only encountered the issue with innoextract on this release and thought it'd be good to report this, but that seems like to be an already known limitation of github
