### ISSUE TITLE
Bonus SPECIAL_FIXED_VALUE_ENCHANT may make spell.slow invalid

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4198]
**Describe the bug**
ruins town heroes thar, her specialty is that
```
"maxSlow": {
	"addInfo": 3,
	"subtype": "spell.slow",
	"type": "SPECIAL_FIXED_VALUE_ENCHANT"
}
```
her expert slow spell will lead some units to 0 speed or below, that units will not afftect by spell slow. 

**To Reproduce**
1. enable ruins-town mod
2.pick heroes thur
3. make her learn expert earch magic
4. cast slow on pikeman or other unit which speed is lower than 6.
5. creature speed is not changed

**Expected behavior**
creature speed change to a minial value, such as 2

**Actual behavior**
creature speed not change 

**Did it work earlier?**
since 1.5.3 

**Screenshots**
![1](https://github.com/vcmi/vcmi/assets/8289682/799a9682-bc72-49b2-a5d8-f2b4c48a61a1)

**Version**
 - OS: Windows
 - Version:1.5.3
 
**Additional context**
no

**Comment by IvanSavenko** [comment]
From what I see, this specialty was never functional.

SPECIAL_FIXED_VALUE_ENCHANT changes bonus granted by a spell.

For example, slow modifies speed of a stack by specified percentage (-25% or -50%)
What this specialty does at the moment is that it changes this percentage to a fixed value of +3% (yes, plus).

Actual bug is probably cause by this limiter:
```json
"propagator": "BATTLE_WIDE",
"limiters": [ 
	[ "noneOf", [ "OPPOSITE_SIDE" ] ]
 ]
```
Unless I missed something, it is completely unnecessary - removing both propagator and limiter will make bonus that only affects troops of this hero.


So:
1. Replace `"addInfo" : 3` with `"addInfo" : -50` in maxSlow bonus
2. Remove propagator & limiter from immunity bonus.
