### ISSUE TITLE
touchscreen introduction for battle is shown on desktop system

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#4382]
this makes no sense of course

1.5.6 release, macOS ARM

**Comment by Laserlicht** [comment]
Can you retest development version?

We've changed the detection.

**Comment by kambala-decapitator** [comment]
erased tutorial fields from `persistentStorage.json` and ran develop build - no tutorials were shown to me. So seems to work correctly in develop?

**Comment by Laserlicht** [comment]
Yes see here: https://github.com/vcmi/vcmi/pull/4299

Before that PR it used `hasTouchInputDevice()`. Because of this the window opened, when there is a Touchscreen present (not necessary used).
Now it uses `getCurrentInputMode() == InputMode::TOUCH`. This will open the window if last input was an touch input.

**Comment by kambala-decapitator** [comment]
I guess `hasTouchInputDevice() == true` when there's trackpad
