### ISSUE TITLE
Video from translation isn't used anymore [development]

### ISSUE THREAD

**Issue by Laserlicht** [vcmi/vcmi#4408]
**Describe the bug**
Video from translation isn't used anymore (with translated audio).

**To Reproduce**
1. Install e.g. german translation
2. start
3. hear to the voice in intro
4. -> english

**Did it work earlier?**
Works in 1.5.6

**Version**
 - Version: develop

**Additional context**
Regression from #3998

**Comment by heroesiiifan** [comment]
fixed in german 1.6

**Comment by IvanSavenko** [comment]
Ah, should've looked into it sooner.
To clarify, vcmi will now load .smk videos only as a last resort. These videos generally have lower quality than .bik clips. So if any other video with same name is found it will always be used instead of smk.

You need to provide some video other than smk - bik, ogv (HD Edition) or webm with vp8/vp9 codec.
If you really want to use smk you can cheat a bit and rename it to .bik without re-encoding.
