### ISSUE TITLE
graphics bugs in xBrz x4

### ISSUE THREAD

**Issue by kdmcser** [vcmi/vcmi#4568]
**Describe the bug**
spell cast interface：
![1](https://github.com/user-attachments/assets/38af3d46-fa9c-444e-8dea-17b25de7dd21)

creature subscript is gray:
![2](https://github.com/user-attachments/assets/29f5c141-ff5f-487c-9b18-27eadb28bd01)

**Comment by Povelitelh3** [comment]
![01](https://github.com/user-attachments/assets/aa86acd0-cbaa-40d4-9357-5186d68808b7)
![02](https://github.com/user-attachments/assets/895ea959-56c1-43d8-a84b-03e8df9f9c32)

**Comment by Povelitelh3** [comment]
And my mouse lags at x4, I feel the lags. Any mode, directX or openGL doesn't matter

**Comment by kdmcser** [comment]
no lags in my computer for x4, my graphics card is 2080.

**Comment by IvanSavenko** [comment]
Heavily depends on hardware. You also won't get any visual improvements with extreme xbrz level.

General recommendation is probably:
FullHD -> xbrz x2
1440p -> xbrz x2
4K -> xbrz x3

xbrz x4 makes sense only for displays larger than 4k

**Comment by IvanSavenko** [comment]
Might get better if/when we'll get hardware acceleration, but for now don't see any way to significantly improve performance for high scaling levels

**Comment by Povelitelh3** [comment]
> General recommendation is probably: FullHD -> xbrz x2 1440p -> xbrz x2 4K -> xbrz x3
> xbrz x4 makes sense only for displays larger than 4k

tnx for info, I didn't knew that.

![изображение](https://github.com/user-attachments/assets/892701c6-a38b-4772-9cda-8066b02e6ca8)

That's why I wrote, because in HD mode, with such settings, it doesn't lag at all. The response is very fast, on my hardware, and immediately in the VCMI and it feels. 
If this is all due to the fact that there is no support for graphics accelerators, then the issue is completely removed.
