### ISSUE TITLE
wrong icons of arrow towers

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#791]
Conflux towers have storm els, but in the turn order they have magma els images (the 3x1 stacks): https://imgur.com/a/QgvV8Gb

haven't checked other towns.

**Comment by Nordsoft91** [comment]
Was fixed earlier

**Comment by IvanSavenko** [comment]
Reopening, still not resolved in develop branch.
Cause of bug is lack of icon for creature 149 (CreatureID::ARROW_TOWERS).

- Solution A: Provide new generic icon for this creature (e.g. simple icon of tower suitable for any town)
- Solution B: Use icon from shooter creature, e.g. Lich icon for Necropolis. May be a bit confusing since same icon can be used by actual creature stack.
- Solution C: Create custom icons for every town in game. Best option visually, but most difficult one since this requires editing original H3 graphics. 

Personal opinion: go with solution A. I can make such icon myself once I have free time, but if somebody else wants to fix this instead - feel free to go ahead. Note that this needs two icons - for large and small battle queues, similar to existing creatures.

**Comment by kambala-decapitator** [comment]
there's also "Arrow Tower Icons" mod in VCMI Extras, maybe it should become a part of Essentials

**Comment by IvanSavenko** [comment]
Hmm... That mod contains:
- "kill" sound, for tower destruction - explosion already has sound, so not sure whether it is necessary.
- "shoot" sound - vcmi should use sound from corresponding creature instead (fixed in my branch)
- tower icons - too different art style compared to H3 in my opinion. I'd rather make monochrome icon & color it with that light-gold color commonly used in H3 UI.

So yeah, it should be in core game but probably with slightly different content.

**Comment by misiokles** [comment]
![towerBigOld](https://user-images.githubusercontent.com/29593042/204387210-e7d73fe3-f888-491e-999e-bf2d70e54c13.png)
![towerSmallOld](https://user-images.githubusercontent.com/29593042/204387236-42178886-88c3-4371-a200-31eb380b91ac.png)
(alternative tower icons - ripped from Inferno's siege screen).

**Comment by IvanSavenko** [comment]
![зображення](https://user-images.githubusercontent.com/1576820/204388394-bb9ea6e9-c4d3-47ec-b24f-cced04338f47.png)
Tested how all of these would look in-game:
- topmost: 3 simple monochrome icons, with slightly different background
- 2nd from top: simple monochrome icon, small battle queue
- 3rd from top: 2 icons from current mod + Inferno icon from misiokles
- 4th from top: same as 3rd

Proposition:
- add "simple monochrome icons" into base game (directly into this repository)
- for Arrow Tower Icons submod I'll add functionality to define tower icon per town, allowing you/Witchking/anyone else to create mod where each town will have proper icon that actually represents this town.
- All new faction mods will also be able to define such "nice" icon. Probably should be made as required by validation.
- monochrome icon will be used as fallback - for cases where player has no "Arrow Tower Icons" mod or for factions that have not defined such icon

This way, base game will function correctly, without weird bugs and you can still get "nice" icon by installing additional mod. And we won't have any ripped assets in this repo.

Opinions? @misiokles especially?

**Comment by misiokles** [comment]
Seems legit with monochrome icons as 'base'. And possibility to make mod with unique icons per town/fraction sounds awesome. And solution with return to monochrome in case of 'no tower icons' is smart!

btw. 2nd monochrome icon looks best!

**Comment by IvanSavenko** [comment]
Great. In that case if there are not other suggestions I'll go with this approach.
