### ISSUE TITLE
VCMI_Tests_2011b.h3m

### ISSUE THREAD

**Issue by josch** [vcmi/vcmi#951]
Hi,

thanks a lot for the 1.0.0 release! It is already packaged in Debian: https://packages.debian.org/source/unstable/vcmi

The new release also shipped a file that was not part of any previous releases:

    Mods/vcmi/Maps/VCMI_Tests_2011b.h3m

What is that file? Is it a map? I tried copying it into `~/.local/share/vcmi/Maps` but it didn't show up in the selection screen. Is it playable? How was it created? How can it be edited and (most important) what is its license?

Thanks!

**Comment by misiokles** [comment]
Yes, map is playable, but it's designed for testing purposes. Because it has 'strange' format, it it located under ALL maps button, you must scroll maps to the end. Ano no, it's not HotA map :)

![image](https://user-images.githubusercontent.com/29593042/191093274-3e0cb366-7dfb-4b3f-aa82-e6132be94a30.png)

**Comment by josch** [comment]
Thank you! Do you also about the licensing of the map? Is it released under the same copyright as the rest of vcmi and who are its authors?

How was the map created?

**Comment by misiokles** [comment]
I think someone from old devs team made it. Sxx, maybe alexvins. This is simple map, made by standard heroes3 map editor, so license is like any other fans .h3m map.

**Comment by ArseniyShestakov** [comment]
@josch basically it's been created by dev team so it's licensed under the same license as engine.
Probably by @DjWarmonger, @IvanSavenko or @mwu-tow.

So for certain there are no problems in including it with game package.
Though it's not exactly useful for the end-users and we probably should distribute it as mod.

**Comment by josch** [comment]
Thank you @ArseniyShestakov -- that's exactly the kind of wording I need. :heart:

**Comment by ArseniyShestakov** [comment]
H3M files themself do not contain any proprietary assets in them.
Obviously all other maps not created for VCMI specifically should not be included because their license is questionable.

Also there is update checking code that you might want to disable in Debian by default, though it's probably only work when you press the button.

Btw we are now store all assets with unclear license in mods repository under separate organization:
https://github.com/vcmi-mods

**Comment by ArseniyShestakov** [comment]
@josch and yeah once again thank you very much for maintaining VCMI package in Debian!

**Comment by josch** [comment]
Yup, in Debian we carry this patch to disable the automatic update checking:

https://sources.debian.org/src/vcmi/latest/debian/patches/disable-privacy-breach/

Or, in case the URL vanishes:

```patch
--- a/config/schemas/settings.json
+++ b/config/schemas/settings.json
@@ -380,7 +380,7 @@
 				},
 				"autoCheckRepositories" : {
 					"type" : "boolean",
-					"default" : true
+					"default" : false
 				},
 				"updateOnStartup" : {
 					"type" : "boolean",
```

**Comment by josch** [comment]
Oh, I am just now realizing that there is now a new option `updateOnStartup` -- I probably want to disable that as well.

**Comment by IvanSavenko** [comment]
Hi. I'ts been a while so I am not 100% sure, but from what I remember, this
map was created & maintained by Warmonger

Пн, 19 вер. 2022 22:07 користувач Arseniy Shestakov <
***@***.***> пише:

**Comment by DjWarmonger** [comment]
@IvanSavenko You still alive? Good to see you :)

**Comment by IvanSavenko** [comment]
@DjWarmonger Hi. Yup, we're getting air raid sirens nowadays, but yeah, still alive :)
