### ISSUE TITLE
buggy morale strings

### ISSUE THREAD

**Issue by kambala-decapitator** [vcmi/vcmi#962]
1. Sepulcher (Crypt) has extra line break
2. Crypt and Warrior Tomb strings contain numbers twice

![Screenshot 2022-09-21 at 12 35 25](https://user-images.githubusercontent.com/1557784/191478186-462f505e-c79e-4262-aa4b-125cb5211301.png)

Also, in oh3 Warrior Tomb has different message:
![Screenshot 2022-09-21 at 15 54 05](https://user-images.githubusercontent.com/1557784/191509289-f491dbed-4e82-4955-881b-83e28d6c2c53.png)

**Comment by IvanSavenko** [comment]
Looks to actually be a bit larger in scale than it appears, probably should be postponed to 1.2 to be safe:

- Extra line breaks are an easy part - see MoraleLuckBox::set method. H3 texts already contain line breaks at the start of strings, should probably trim them to ensure that only one line break gets added.
- H3 strings also already contain morale modifier (e.g. "-1") in string. Meaning that bonus description generation should be somehow made aware of such strings and avoid addition of second suffix.
- "Temporary until next battle" that should be replaced with "Warrior Tomb Visited": currently these objects default to generic description. Bonus class allows custom description but problem is, this is simple std::string that is generated on server. Correct fix would be to turn this in MetaString that can be properly translated by client. However this is definitely major change since it will affect everything that uses Bonus class, meaning - pretty much everything in the game.
