### ISSUE TITLE
vcmibuilder: validation error, VCMI data files are always missing

### ISSUE THREAD

**Issue by boozook** [vcmi/vcmi#982]
`vcmibuilder` with option `--validate` always fails with error `Error: VCMI data files are missing!`, but all files are valid and VCMI successfully run and load resources.
I'm sure it because of old paths or some other legacy there.

Branch: develop
Revision: actual, 4205701f96a872dface1504e4d7f2e7be81a67f4
Where: [there][]

OS: macOS 12.5.1 (aarm64, M1)

[there]: https://github.com/vcmi/vcmi/blob/develop/vcmibuilder#L275

- - -

Also in my case [that][patterns] `[Dd][Aa][Tt][Aa]` pattern-matching doesn't works in my bash or zsh (tried both) on Mac. Always ends with err "dir not found" or something like that.

[patterns]: https://github.com/vcmi/vcmi/blob/develop/vcmibuilder#L234-L236

**Comment by kambala-decapitator** [comment]
> Also in my case [that](https://github.com/vcmi/vcmi/blob/develop/vcmibuilder#L234-L236) `[Dd][Aa][Tt][Aa]` pattern-matching doesn't works in my bash or zsh (tried both) on Mac. Always ends with err "dir not found" or something like that.

the calling shell doesn't matter because the script requests bash explicitly. I also didn't see such issues when testing on 12.5.1 (doubt that Intel CPU makes a difference) against GOG installer.

**Comment by boozook** [comment]
> the calling shell doesn't matter because the script requests bash explicitly. I also didn't see such issues when testing on 12.5.1 (doubt that Intel CPU makes a difference) against GOG installer.

I just tested it in zsh removing shebang. 
In my case folders was named Data and others is same, leading upper. Pattern doesn't matching.

**Comment by IvanSavenko** [comment]
Can confirm this bug actually.
vcmibuilder copies folders irregardless of case (DATA/Data/data), but --validate option checks only for "Data".
Also, H3bitmap.lod / H3sprite.lod / VIDEO.VID may also in theory have different case, causing validation error.

Can you post file listing of copied directories?
1) Directory with Data/Maps/Mp3 directories
2) Data directory content
I'd like to check letter case of all files in these directories

Fix should likely be postponed till #884 is fixed, since validation issue is likely related

**Comment by IvanSavenko** [comment]
Hi. Can you check whether updated script works for you?
You can download it here:
https://raw.githubusercontent.com/vcmi/vcmi/96caceba79adb6e73b1a09f1a7b0134134b983ae/vcmibuilder
